apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-api
  labels:
    app: oauth-api
    owner: sk-example-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-api
  template:
    metadata:
      labels:
        app: oauth-api
    spec:
      containers:
        - name: oauth-api
          image: oauth-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: dev
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
